import Head from "next/head";
import Image from "next/image";
import Header from "../components/header/header";
import Hero from "../components/hero/hero";
import Footer from "../components/footer/footer";
import Masonry from "../components/masonry/masonry";

export default function Providers() {
  return (
    <>
      <Head>
        <title>For Providers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Header headerBg="dark" />

      <div className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20">
        <main className="flex flex-col gap-[32px] row-start-2 items-center sm:items-start">
          <Hero />
        </main>
      </div>
      
      <Masonry />

      <Footer />
    </>
  );
}
